name: Deploy react Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub 
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t karthik160/uandi-frontend .

      - name: Publish Image to Docker Hub
        run: docker push karthik160/uandi-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull karthik160/uandi-frontend:latest        

      - name: Run Container from Docker Image
        run: docker run -d -p 3000:80 --name uandi-frontend-container karthik160/uandi-frontend
